version: 0.1
phases:
  install:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket suvankar-books-api
      - sam deploy --template-file packaged.yaml --stack-name suvankar-books-api --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml