version: 0.1
phases:
  install:
    commands:
      - yum update -y
      - sha256sum aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version
      - sam package --output-template-file packaged.yaml --s3-bucket suvankar-books-api
      - sam deploy --template-file packaged.yaml --stack-name suvankar-books-api --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml