AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoBooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: books
      PrimaryKey:
        Name: id
        Type: String
  CreateBookFunction: # 1
    Type: AWS::Serverless::Function # 2
    Properties:
      CodeUri: src/ # 3
      Handler: create-book.handler # 4
      Policies: AmazonDynamoDBFullAccess # 5
      Runtime: nodejs12.x
      Events:
        CreateBook: # 6
          Type: Api
          Properties:
            Path: /books #7
            Method: post